// AUTO-GENERATED by scripts/build-teacher-npc-sheet.mjs — do not edit.
// Source art: 2D/ตัวละคร/ครู/ครูชาย/npc_teacher_weeraphat_*_8f.png
// Frames are re-registered on the feet centroid with a shared baseline, so
// every animation stands on the exact same spot.
export const TEACHER_SHEET = {
  columns: 8,
  frameWidth: 106,
  frameHeight: 162,
  baselineRow: 156,
  rows: { idle: 0, celebrate: 1 },
} as const

export type TeacherSheetRow = keyof typeof TEACHER_SHEET.rows
